### ISSUE TITLE
Command without slash

### ISSUE THREAD

**Issue by azhe403** [VodemSharp/Allowed.Telegram.Bot#1]
With the following code, we can invoke commands with `/start` or `/ping`

```
    [Command("start")]
    [Command("ping")]
    public async Task Start(MessageData data)
    {
        await data.Client.SendTextMessageAsync(data.Message.From!.Id, "You pressed: /start");
    }
```

How do I configure it so that it can be invoked with ping without slash?
maybe `[Command("ping", withoutSlash: true)]`

**Comment by VodemSharp** [comment]
Unfortunately, the library does not yet support non-slash commands like this. This can be implemented using [TextCommand] and direct comparison of message text. I will add this functionality to the backlog of future updates.

**Comment by VodemSharp** [comment]
We have released a new version of the library. Now you can use the attribute [TextCommand] like [TextCommand("ping")].
