### ISSUE TITLE
Command with param

### ISSUE THREAD

**Issue by azhe403** [VodemSharp/Allowed.Telegram.Bot#2]
I have a ping command with code like this.
```
[Command("ping")]
public async Task Ping(MessageData data)
{
  await _mediator.EnqueueAsync();
}
```
when invoking with `/ping` that can be invoked, but no longer when with `/ping test`. 
ping command maybe should be invoked with or without command param.

**Comment by VodemSharp** [comment]
Good point! I added this feature in today's update.
Slash and text commands now also return a 'Params' property.
Previously, this trick could only be performed with [DefaultCommand].

**Comment by azhe403** [comment]
sorry for my request, before.

i will request again for callback/inline too.
they should be invoked with first word of callback/inline depending on word separator.

an example `search telegram bot`, they should be invoked with `search` command callback/inline and `telegram bot` as param(s). if word separator is `space`

thanks, Vodem!

**Comment by VodemSharp** [comment]
As for the callback, I don't see the point of adding a search by the first word (in the button?). There is a convenient system for callbacks with paths that can be used very flexibly to execute different logic.
For inline methods, it might be really useful doing something based on filters at the beginning of the request. I will think about it.
Feel free to make suggestions and requests. I will take that into consideration.

**Comment by azhe403** [comment]
As for callback, usually I use for delete message. For an example `delete-mesage 123`, so we can use button for deleting message  with id 123 in current chat

**Comment by VodemSharp** [comment]
You can use model that extends CallbackQueryModel, and you can pass the required information to them. A method with the [CallbackQuery] attribute can use a parameter of this model. You can see an example in the sample with db, it also works in no db projects.
The time will come and I will write normal documentation🥲
