### ISSUE TITLE
Command expression

### ISSUE THREAD

**Issue by azhe403** [VodemSharp/Allowed.Telegram.Bot#3]
Hi Vodem,
do you have plan to adding command expression like this snippet?

```
[Command(x => x.StartWith("#")]
public async Task GetHash(MessageData data)
{
    // todo
}
```

and might can be implemented to media caption too?

**Comment by VodemSharp** [comment]
Hi, I think it might be similar to:

`[TextCommand("#", Type = ComparisonTypes.Parameterized)]`

There is an example in SampleController.
This is not implemented for media caption, but I will work on optimizing and improving this project in the near future.
I will think about it.
